package dev.halfcraft.link;

/**
 * HalfCraft's shared memory as protocol/halfcraft_protocol.h lays it out. Generated by tools/build/protocol.py
 * from protocol/schema/*.toml: change the schema and run make proto, never this file.
 */
public final class Proto {
	private Proto() {
	}

	// a hash of the layout below but its comments: the host writes it into the header, and Minecraft links only
	// with a host built from the same schema
	public static final int LAYOUT = 0x0E992381;

	// ---- where each part of the mapping is
	public static final long OFF_HEADER = 0x00;
	public static final long OFF_HOST_STATE = 0x100; // host -> MC, seqlock: seq odd while writing
	public static final long OFF_MC_STATE = 0x200; // MC -> host, seqlock
	public static final long OFF_OVERLAY_CTL = 0x300;
	public static final long OFF_OVERLAY_SLOT_HDR = 0x340; // one per slot
	public static final long OFF_WATER_GRID = 0x400; // host -> MC, see WaterGrid
	public static final long OFF_INPUT_RING = 0x1000; // host -> MC, see InputEvent
	public static final long INPUT_RING_BYTES = 0x10080; // IR_DATA + sizeof(InputEvent) * INPUT_RING_ENTRIES
	public static final long OFF_ACTOR_TABLE = 0x12000; // host -> MC, seqlock
	public static final long OFF_EVENT_RING = 0x17000; // MC -> host, see McEvent
	public static final long EVENT_RING_BYTES = 0x6080; // ER_DATA + sizeof(McEvent) * EVENT_RING_ENTRIES
	public static final long OFF_WORLD_ENTITIES = 0x1E000; // MC -> host, seqlock
	public static final long OFF_HOST_DEBUG = 0x22000; // host -> MC, seqlock
	public static final long HOST_DEBUG_BYTES = 0x1000;
	public static final long OFF_WEAPON_TABLE = 0x23000; // host -> MC, seqlock
	public static final long WEAPON_TABLE_BYTES = 0x1000;
	public static final long OFF_MOB_TABLE = 0x24000; // MC -> host, seqlock
	public static final long MOB_TABLE_BYTES = 0x5000;
	public static final long OFF_WATER_PROBES = 0x29000; // seqlocks: Minecraft writes the requests, client.dll the answers
	public static final long WATER_PROBES_BYTES = 0x1000;
	// 0x2A000-0x30FFF: kept for the world group (C)
	public static final long OFF_COLLISION_RING = 0x40000; // host -> MC, a byte ring
	public static final long COLLISION_RING_BYTES = 0x2000000; // 32 << 20
	public static final long OFF_OVERLAY_PIXELS = 0x2040000; // MC -> host: the slots' RGBA8 pixels
	public static final long OVERLAY_PIXELS_BYTES = 0x5EEC000; // OVERLAY_SLOT_BYTES * OVERLAY_SLOTS
	public static final long OFF_RENDER_RING = 0x7F2C000; // MC -> host, a byte ring
	public static final long RENDER_RING_BYTES = 0x4000000; // 64 << 20
	public static final long MAPPING_BYTES = 0xBF2C000;

	// ---- header @0x00 -------------------------------------------------------------------------------
	// Derived from SkyCraft's protocol (see the README). All multi-byte values are little-endian. The host
	// creates the mapping; Minecraft opens it. Coordinates in this protocol are always Minecraft space
	// (blocks, Y up, Z south) unless noted.
	public static final int MAGIC = 0x464C4148; // "HALF"
	public static final String MAPPING_NAME = "Local\\HalfCraft_v1";
	// an auto-reset event the host sets after each frame's HostState: minecraft waits on it to draw once
	// per host frame, asleep in between
	public static final String FRAME_EVENT_NAME = "Local\\HalfCraft_v1_frame";

	// Header: offsets in it (in OFF_HEADER)
	public static final long H_MAGIC = 0x00;
	public static final long H_LAYOUT = 0x04; // LAYOUT: Minecraft links only with a host built from the same schema
	public static final long H_HOST_PID = 0x08;
	public static final long H_MC_PID = 0x0C;
	public static final long H_HOST_HEARTBEAT = 0x10; // GetTickCount64() at the host's last frame
	public static final long H_MC_HEARTBEAT = 0x18; // GetTickCount64() at MC's last frame
	// a new value each time a host sets the link up; Minecraft starts its side over when it changes.
	// the pid alone can't tell: a restarted game may get the pid of the one before it
	public static final long H_HOST_SESSION = 0x20;
	public static final int H_BYTES = 0x28;

	// ---- host -> MC state @0x100 --------------------------------------------------------------------
	public static final int WATER_GRID_SIZE = 16;
	public static final float NO_WATER = -1e+30F;

	// HostFlags
	public static final int HOST_IN_GAME = 1 << 0; // a map is loaded and the player exists
	public static final int HOST_MENU_OPEN = 1 << 1; // a host menu (or console) owns input; MC should drop held keys
	public static final int HOST_LOADING = 1 << 2; // loading screen / level transition in progress
	public static final int HOST_SEATED = 1 << 3; // in a vehicle's seat (with HOST_TAKEOVER): Minecraft's body sits, facing seatYaw
	// source moves the player itself (a ladder, a lift or train, a vehicle, a scripted scene): Minecraft's
	// player stays at posX/Y/Z every tick, without falling or fall damage, until the hand-back's teleport
	public static final int HOST_TAKEOVER = 1 << 7;
	// bit 8: kept for the puppet group (A), 9-10 for the world group (C)

	// HostState: offsets in it (in OFF_HOST_STATE)
	public static final long HS_SEQ = 0x00;
	public static final long HS_FLAGS = 0x04; // HostFlags
	public static final long HS_WORLD_ID = 0x08; // the host's map (a hash of its name); never 0 in game
	public static final long HS_COLLISION_EPOCH = 0x0C; // bumps on every level load; MC drops all collision data
	public static final long HS_POS_X = 0x10; // the host player's feet, MC coords
	public static final long HS_POS_Y = 0x18;
	public static final long HS_POS_Z = 0x20;
	public static final long HS_YAW = 0x28; // authoritative look (MC degrees)
	public static final long HS_PITCH = 0x2C;
	public static final long HS_TELEPORT_SEQ = 0x30; // MC teleports its player to pos when this changes
	public static final long HS_VIEWPORT_W = 0x34;
	public static final long HS_VIEWPORT_H = 0x38;
	public static final long HS_GAME_HOUR = 0x3C;
	public static final long HS_SEAT_YAW = 0x40; // the way the vehicle's seat faces (MC degrees), with HOST_SEATED
	public static final long HS_SPEED_FACTOR = 0x44; // how fast source lets its player move (player_speedmod): 1 normal, 0.5 half speed
	// minecraft draws its overlay at the viewport's size over this (hc_overlay_scale), a gui scale it
	// was given divided alike, and the host scales it back up pixel for pixel. 0 (an older host): 1
	public static final long HS_OVERLAY_DIVISOR = 0x48;
	public static final int HS_BYTES = 0x50;

	// WaterGrid: offsets in it (in OFF_WATER_GRID)
	// The host's water around the player, for Minecraft to treat as its own water: swimming,
	// floating, drowning. Seqlock like HostState.
	public static final long WG_SEQ = 0x00;
	public static final long WG_ORIGIN_X = 0x04; // Minecraft block column of surface[0]
	public static final long WG_ORIGIN_Z = 0x08;
	public static final long WG_WORLD_ID = 0x0C; // as in HostState
	public static final long WG_SURFACE = 0x10; // [z * size + x]: MC y of the water surface; NO_WATER: none
	public static final int WG_BYTES = 0x410;

	// ---- MC -> host state @0x200 --------------------------------------------------------------------
	// McFlags
	public static final int MC_IN_WORLD = 1 << 0;
	public static final int MC_SCREEN_OPEN = 1 << 1; // an MC GUI screen (inventory, chat, ...) is open
	public static final int MC_ON_GROUND = 1 << 2;
	public static final int MC_SNEAKING = 1 << 3;
	public static final int MC_SPRINTING = 1 << 4;
	public static final int MC_DEAD = 1 << 5;
	public static final int MC_SWIMMING = 1 << 6;
	public static final int MC_FLYING = 1 << 7;
	public static final int MC_SLEEPING = 1 << 8; // in a bed: yaw/pitch are the look Minecraft holds there, eyeX/Y/Z its camera
	// bits 12-13: kept for the puppet group (A), 14-15 for the world group (C)

	// McState: offsets in it (in OFF_MC_STATE)
	public static final long MS_SEQ = 0x00;
	public static final long MS_FLAGS = 0x04; // McFlags
	public static final long MS_X = 0x08; // interpolated feet position (MC coords)
	public static final long MS_Y = 0x10;
	public static final long MS_Z = 0x18;
	public static final long MS_YAW = 0x20; // MC rotation (degrees); asleep in first person its camera's, along the bed
	public static final long MS_PITCH = 0x24;
	public static final long MS_EYE_HEIGHT = 0x28; // blocks above feet
	public static final long MS_SENSITIVITY = 0x2C; // MC mouse sensitivity option (0..1)
	public static final long MS_TELEPORT_ACK = 0x30; // last HostState::teleportSeq applied
	public static final long MS_GUI_SCALE = 0x34;
	public static final long MS_FRAME_COUNTER = 0x38;
	public static final long MS_FOV = 0x40; // effective vertical FOV (includes sprint / fluid modifiers)
	public static final long MS_BOB_PHASE = 0x44; // MC walk-bob phase (interpolated walk distance); 0 if bobbing is off
	public static final long MS_BOB_AMOUNT = 0x48; // MC walk-bob amplitude
	public static final long MS_EYE_X = 0x50; // MC camera position (interpolated, includes sneak eye lerp)
	public static final long MS_EYE_Y = 0x58;
	public static final long MS_EYE_Z = 0x60;
	// Raw 20 Hz physics ticks, so the host can interpolate on its own frame clock exactly like
	// Minecraft's renderer does with partial ticks (no judder from the two games' frame phase).
	// tickQpc: QueryPerformanceCounter at the (remainder-corrected) tick
	public static final long MS_TICK_QPC = 0x68;
	public static final long MS_PREV_X = 0x70; // feet at the previous tick
	public static final long MS_PREV_Y = 0x78;
	public static final long MS_PREV_Z = 0x80;
	public static final long MS_CUR_X = 0x88; // feet at the latest tick
	public static final long MS_CUR_Y = 0x90;
	public static final long MS_CUR_Z = 0x98;
	public static final long MS_EYE_HEIGHT_O = 0xA0; // Camera's smoothed eye height, previous/latest tick
	public static final long MS_EYE_HEIGHT_T = 0xA4;
	public static final long MS_WALK_O = 0xA8; // walk-bob phase inputs
	public static final long MS_WALK = 0xAC;
	public static final long MS_BOB_O = 0xB0; // walk-bob amplitude inputs
	public static final long MS_BOB = 0xB4;
	public static final long MS_TICK_MS = 0xB8; // milliseconds per tick (50 unless /tick rate changed)
	// Minecraft's camera (F5): 0 first person, 1 third person behind, 2 third person in front
	// (looking back at the player). cameraDistance is how far Minecraft's camera sits from
	// the eye, after its own zoom collision (Minecraft blocks and the host's triangles).
	public static final long MS_CAMERA_MODE = 0xC0;
	public static final long MS_CAMERA_DISTANCE = 0xC4;
	// The player's health and absorption (golden hearts), in Minecraft points (20 = 10 hearts).
	public static final long MS_HEALTH = 0xC8;
	public static final long MS_MAX_HEALTH = 0xCC;
	public static final long MS_ABSORPTION = 0xD0;
	// (#12) the host's weapon the player holds as a Minecraft item (see WeaponTable); 0: none
	public static final long MS_HELD_WEAPON = 0xD8;
	// Bumps each time Minecraft moved its player by itself (an ender pearl, chorus fruit, /tp; not the
	// host's own teleports), in the same tick as curX/Y/Z: the host takes the jump that follows wherever
	// the player fits, and resyncs Minecraft where it doesn't.
	public static final long MS_TELEPORT_COUNT = 0xE0;
	public static final int MS_BYTES = 0xF0;
	// 0xF0-0xFF: kept for the world group (C)

	// ---- overlay triple buffer @0x300 ---------------------------------------------------------------
	// state: bits 0-1 = index of the "middle" slot, bit 2 = middle holds an unread frame.
	// Writer (MC) renders into its private back slot, then xchg(state, back | OVERLAY_DIRTY) and keeps
	// the returned index as its new back slot. Reader (the host) does xchg(state, front) only when
	// the dirty bit is set and keeps the returned index as its new front slot.
	public static final int MAX_OVERLAY_W = 3840;
	public static final int MAX_OVERLAY_H = 2160;
	public static final long OVERLAY_SLOT_BYTES = 0x1FA4000; // MAX_OVERLAY_W * MAX_OVERLAY_H * 4
	public static final int OVERLAY_SLOTS = 3;
	public static final int OVERLAY_DIRTY = 1 << 2;

	// OverlayCtl: offsets in it (in OFF_OVERLAY_CTL)
	public static final long OC_STATE = 0x00;
	public static final long OC_FRAMES_PUBLISHED = 0x08;
	public static final int OC_BYTES = 0x10;

	// OverlaySlotHdr: offsets in it (in OFF_OVERLAY_SLOT_HDR)
	public static final long SH_WIDTH = 0x00;
	public static final long SH_HEIGHT = 0x04;
	public static final long SH_FLAGS = 0x08; // bit0: rows are bottom-up
	public static final long SH_FRAME_ID = 0x10;
	public static final int SLOT_HDR_SIZE = 0x40;

	// ---- input ring @0x1000 -------------------------------------------------------------------------
	// The host produces, MC consumes: InputEvent[INPUT_RING_ENTRIES] after the two indices.
	public static final int INPUT_RING_ENTRIES = 4096; // power of two
	public static final long IR_HEAD = 0x00; // u64, written by the host
	public static final long IR_TAIL = 0x40; // u64, written by MC
	public static final long IR_DATA = 0x80;
	public static final int PUSH_REPEAT_MS = 200; // IN_PUSH
	public static final int PUSH_STALE_MS = 500; // IN_PUSH
	// Blocks the host's gravity gun holds at once (IN_TAKE_BLOCK's slots); taking one more drops the oldest.
	public static final int MAX_HELD_BLOCKS = 32;
	public static final int STRING_CHANNEL_MASK = 0xFF; // IN_STRING's code: its StringChannel
	public static final int STRING_BYTES_SHIFT = 8; // 4 bits: 0-12 bytes
	public static final int STRING_END = 1 << 15;
	public static final int STRING_PIECE_BYTES = 12;

	// InputType
	public static final int IN_KEY = 1; // code = SDL scancode, a = 1 press / 0 release
	public static final int IN_MOUSE_BUTTON = 2; // code = SDL button (1 L, 2 M, 3 R, 4 X1, 5 X2), a = 1 press / 0 release
	public static final int IN_SCROLL = 3; // a = wheel notches * 120 (positive = up)
	public static final int IN_CURSOR = 4; // a, b = absolute cursor position in overlay pixels
	public static final int IN_TEXT = 5; // a = unicode code point
	public static final int IN_RELEASE_ALL = 6; // release every held key/button (input focus left MC)
	public static final int IN_HURT = 7; // the host hit the player: code = HurtKind, a = host damage * 100, b = attacker actor id, c = HurtFlags
	public static final int IN_OPEN_MENU = 8; // open Minecraft's pause/options menu
	public static final int IN_HEAL = 9; // the host healed the player: code = HealKind, a = host points * 100 (Minecraft divides by 5, like damage)
	// the host saved its game: a/b = the save's checkpoint id (low/high 32 bits); Minecraft
	// keeps its world's changed blocks and its player as they are now under that id
	public static final int IN_CHECKPOINT = 10;
	public static final int IN_RESTORE = 11; // the host loaded a save: a/b = its checkpoint id; Minecraft goes back to that checkpoint
	// a piece of a UTF-8 string for one of Minecraft's StringChannels: code = channel
	// | (bytes in this piece << 8) | STRING_END on the last piece, a/b/c = up to 12 bytes
	// (little-endian, a's low byte first)
	public static final int IN_STRING = 12;
	// (#13) the host hurt a Minecraft mob: code = HurtKind, a = its Minecraft entity id,
	// b = host damage * 100, c = the attacker's actor id (0: none, MOB_ATTACKER_PLAYER: the host's player)
	public static final int IN_HURT_MOB = 13;
	// a host blast (a grenade, a rocket, a barrel): code = its radius (blocks * 100), a/b/c = its centre
	// (Minecraft x/y/z, float bits). Minecraft breaks its blocks there the way TNT would; the host
	// already hurt Minecraft's player and the mobs it has stand-ins for (IN_HURT, IN_HURT_MOB)
	public static final int IN_BLAST = 14;
	public static final int IN_BULLET_HIT = 15; // a host bullet went into a Minecraft block: a/b/c = the block's x/y/z. Glass, panes and ice break
	// the host's player entered a map afresh: code = MapEntry, a = the map's slot (its stretch of
	// Minecraft's world along x), b/c = the slot's west and east edges (Minecraft x, east exclusive).
	// A new game starts a playthrough, and each map the playthrough enters for the first time
	// goes back to how it was before anything was built there (saves keep rolling back as before)
	public static final int IN_MAP_ENTERED = 16;
	// the host's gravity gun tore the block at a/b/c out into held slot code (< MAX_HELD_BLOCKS): Minecraft
	// takes it out of its world and answers EV_HELD_BLOCK; while it's held, WE_HELD_BLOCK has its faces
	public static final int IN_TAKE_BLOCK = 17;
	// held slot code came to rest in the block cell a/b/c: Minecraft puts the block back there,
	// or drops it as an item without room, and answers EV_HELD_BLOCK
	public static final int IN_HELD_BLOCK_LANDED = 18;
	// held slot code went without coming to rest (a level change, dissolved): Minecraft drops the
	// block as an item in the cell a/b/c, where the body was last
	public static final int IN_HELD_BLOCK_LOST = 19;
	// the host dropped render messages it couldn't read (the ring lost its place): Minecraft
	// sends its whole world again
	public static final int IN_RENDER_LOST = 20;
	// the host pushes its player (a trigger_push, a conveyor, a point_push: Source's base velocity)
	// while Minecraft drives it: a/b/c = Minecraft blocks per second * 1000 along x/y/z, repeated
	// every PUSH_REPEAT_MS while it lasts. (0, 0, 0): it stopped, and the player keeps the last
	// push as momentum (as Source does); nothing for PUSH_STALE_MS: it's over, without momentum
	public static final int IN_PUSH = 22;
	// the host shoved its player while Minecraft drives it, a shove that's over at once (a
	// trigger_push that pushes once, an antlion guard: Source's velocity impulses): a/b/c =
	// Minecraft blocks per second * 1000 along x/y/z, which the player takes as momentum
	public static final int IN_IMPULSE = 23;
	// where the next IN_HURT came from, for Minecraft's shield: a/b/c = Minecraft x/y/z (float bits)
	// of the blast's centre or of what dealt it; only that one IN_HURT uses it
	public static final int IN_HURT_FROM = 24;
	// 26-27: kept for the world group (C)

	// MapEntry
	// How the host's player entered a map (IN_MAP_ENTERED).
	public static final int ENTRY_NEW_GAME = 1; // a new game from the host's menu (its chapter list): a new playthrough begins here
	public static final int ENTRY_TRANSITION = 2; // a level transition: the map is the playthrough's own the first time it comes up

	// StringChannel
	// What a IN_STRING is for; Minecraft collects the pieces of each channel until STRING_END.
	public static final int STR_COMMAND = 1; // (#11) run as the player, like a command typed into chat (without the '/')
	// (#6) the answer to Minecraft's EV_SCREENSHOT, or the host's own (request 0), as text:
	//   "ok <request> <width> <height> <path>": the frame in a temporary file named
	//   halfcraft-screenshot-*.rgb, width * height RGB8 pixels, top row first, nothing else;
	//   Minecraft saves it as its own screenshot and deletes the file
	//   "fail <request> <reason>": the host had no frame to give (loading, ...)
	public static final int STR_SCREENSHOT = 2;
	// 6: kept for the puppet group (A), 8 for the world group (C)

	// HealKind
	public static final int HEAL_HEALTH = 0;
	public static final int HEAL_ARMOR = 1; // the host's armour (Half-Life's suit): Minecraft absorption

	// HurtKind
	public static final int HURT_MELEE = 0;
	public static final int HURT_PROJECTILE = 1;
	public static final int HURT_MAGIC = 2;
	public static final int HURT_OTHER = 3;
	public static final int HURT_BLAST = 4; // grenades, rockets, barrels: Minecraft's explosion damage (blast protection; a shield facing IN_HURT_FROM)
	public static final int HURT_FIRE = 5; // burning: Minecraft's fire damage (fire protection)
	public static final int HURT_CRUSH = 6; // physics props, vehicles, crushers: damage armour takes

	// HurtFlags
	public static final int HURT_POWER_ATTACK = 1 << 1; // shoves harder (Minecraft knockback)

	// InputEvent: offsets in it
	public static final long INPUT_EVENT_TYPE = 0x00; // InputType
	public static final long INPUT_EVENT_CODE = 0x02;
	public static final long INPUT_EVENT_A = 0x04;
	public static final long INPUT_EVENT_B = 0x08;
	public static final long INPUT_EVENT_C = 0x0C;
	public static final int INPUT_EVENT_BYTES = 0x10;

	// ---- actor table @0x12000 -----------------------------------------------------------------------
	// Nearby host characters (and breakable things), mirrored in Minecraft as invisible hittable
	// stand-in entities.
	public static final int MAX_ACTORS = 256;

	// ActorFlags
	public static final int ACTOR_HOSTILE = 1 << 0; // hostile to the player right now
	public static final int ACTOR_DEAD = 1 << 1;
	public static final int ACTOR_ESSENTIAL = 1 << 2;
	public static final int ACTOR_IN_COMBAT = 1 << 3;

	// ActorRecord: offsets in it
	public static final long ACTOR_RECORD_ID = 0x00; // the host's handle for it, stable while it exists
	public static final long ACTOR_RECORD_FLAGS = 0x04; // ActorFlags
	public static final long ACTOR_RECORD_X = 0x08; // feet, MC coords
	public static final long ACTOR_RECORD_Y = 0x0C;
	public static final long ACTOR_RECORD_Z = 0x10;
	public static final long ACTOR_RECORD_YAW = 0x14; // MC degrees
	public static final long ACTOR_RECORD_WIDTH = 0x18; // blocks
	public static final long ACTOR_RECORD_HEIGHT = 0x1C; // blocks
	public static final long ACTOR_RECORD_HEALTH_FRAC = 0x20; // 0..1
	public static final long ACTOR_RECORD_LEVEL = 0x24;
	public static final long ACTOR_RECORD_NAME = 0x28; // display name, UTF-8, NUL-terminated (truncated)
	public static final int ACTOR_RECORD_NAME_BYTES = 24;
	public static final int ACTOR_RECORD_BYTES = 0x40;

	// ActorTable: offsets in it (in OFF_ACTOR_TABLE)
	public static final long AT_SEQ = 0x00;
	public static final long AT_COUNT = 0x04;
	public static final long AT_RECORDS = 0x40;
	public static final int AT_BYTES = 0x4040;

	// ---- event ring @0x17000 ------------------------------------------------------------------------
	// MC produces, the host consumes: McEvent[EVENT_RING_ENTRIES] after the two indices.
	public static final int EVENT_RING_ENTRIES = 512; // power of two
	public static final long ER_HEAD = 0x00; // u64, written by MC
	public static final long ER_TAIL = 0x40; // u64, written by the host
	public static final long ER_DATA = 0x80;

	// McEventType
	public static final int EV_HIT_ACTOR = 1; // actorId, a = MC damage (after MC's own modifiers), b/c = knockback dir x/z (MC), d = knockback strength
	public static final int EV_PLAYER_DIED = 2; // the Minecraft player died: kill the host's player
	// a Minecraft explosion (TNT, creeper, ...): a/b/c = centre (MC coords), d = radius (blocks),
	// attackerId = the Minecraft entity id of the mob that set it off (a creeper); 0: nobody (TNT)
	public static final int EV_EXPLOSION = 3;
	// an arrow stuck in a host actor: actorId, a/b/c = where it hit (MC coords), d = flight yaw,
	// flags = flight pitch (float bits), weapon = arrow texture (0 plain, 1 tipped, 2 spectral)
	public static final int EV_ARROW_STUCK = 4;
	// (#6) Minecraft's screenshot key: actorId = Minecraft's request number (1+); the host saves its
	// own finished frame (its world, its hud and Minecraft's overlay) and answers on STR_SCREENSHOT
	public static final int EV_SCREENSHOT = 5;
	// a projectile waits at a/b/c (MC coords), under the space described around the player:
	// the host streams its collision below there too
	public static final int EV_COLLISION_WANTED = 16;
	// news of a held slot (IN_TAKE_BLOCK): actorId = the slot, flags = HeldBlockNews,
	// weapon = HeldMaterial with HELD_TAKEN
	public static final int EV_HELD_BLOCK = 17;
	// Minecraft dropped collision messages it couldn't read (the ring lost its place): the
	// host streams its collision afresh
	public static final int EV_COLLISION_LOST = 18;
	// 6-7: kept for #12 (the host's weapons), 8-9 for #13 (Minecraft's mobs), 12-13 for the puppet group (A)

	// HeldBlockNews
	// What Minecraft did with a held slot (EV_HELD_BLOCK).
	public static final int HELD_TAKEN = 1; // the block left Minecraft's world: the host's physics body is it now
	public static final int HELD_REFUSED = 2; // Minecraft kept the block (it changed since, or may not be taken): the host drops the body
	public static final int HELD_PLACED = 3; // the block is back in Minecraft's world where the body came to rest (IN_HELD_BLOCK_LANDED)
	public static final int HELD_DROPPED = 4; // no room there (or the body went without coming to rest): the block lies there as an item

	// HeldMaterial
	// What a held block is made of, for the host's physics: it sounds, slides and weighs like that.
	public static final int MAT_STONE = 0;
	public static final int MAT_WOOD = 1;
	public static final int MAT_GLASS = 2;
	public static final int MAT_DIRT = 3;
	public static final int MAT_GRAVEL = 4;
	public static final int MAT_SAND = 5;
	public static final int MAT_GRASS = 6; // grass blocks, leaves, moss
	public static final int MAT_METAL = 7;
	public static final int MAT_WOOL = 8;
	public static final int MAT_SNOW = 9;

	// HitFlags
	public static final int HIT_CRITICAL = 1 << 0;
	public static final int HIT_PROJECTILE = 1 << 1;
	public static final int HIT_SWEEP = 1 << 2;
	public static final int HIT_FIRE = 1 << 3;

	// HitWeapon
	// What landed a EV_HIT_ACTOR (the host picks the damage type and impact effects by it).
	public static final int WEAPON_UNARMED = 0;
	public static final int WEAPON_BLADE = 1; // swords
	public static final int WEAPON_AXE = 2;
	public static final int WEAPON_BLUNT = 3; // maces, pickaxes, shovels, hoes, anything else held
	public static final int WEAPON_PIERCE = 4; // tridents, spears
	public static final int WEAPON_ARROW = 5; // arrows and other projectiles

	// McEvent: offsets in it
	public static final long MC_EVENT_TYPE = 0x00; // McEventType
	public static final long MC_EVENT_ACTOR_ID = 0x04;
	public static final long MC_EVENT_A = 0x08;
	public static final long MC_EVENT_B = 0x0C;
	public static final long MC_EVENT_C = 0x10;
	public static final long MC_EVENT_D = 0x14;
	public static final long MC_EVENT_FLAGS = 0x18;
	public static final long MC_EVENT_WEAPON = 0x1C; // HitWeapon for EV_HIT_ACTOR
	// (#13) EV_HIT_ACTOR: the Minecraft entity id of the mob that landed it; 0: the player.
	// EV_EXPLOSION: the mob that set it off
	public static final long MC_EVENT_ATTACKER_ID = 0x20;
	public static final int EVENT_BYTES = 0x30;

	// ---- world entities @0x1E000 --------------------------------------------------------------------
	// Minecraft things the host draws itself each frame (arrows, dropped items, block cracks) + the
	// block outline.
	public static final int MAX_WORLD_ENTITIES = 160;

	// WorldEntityKind
	public static final int WE_ARROW = 1; // uv[0]: the arrow's item icon
	public static final int WE_ITEM = 2; // dropped/thrown item: a flat sprite (uv[0]) turning about the vertical
	public static final int WE_TRIDENT = 3; // uv[0]: the trident's item icon
	public static final int WE_BLOCK = 4; // dropped block item: a spinning cube of side `scale`, uv[0..2] = side, top, bottom
	public static final int WE_CRACK = 5; // block-breaking cracks over the box at (x, y, z) of size ext, uv[0] = crack stage
	public static final int WE_SHADOW = 6; // a player's or mob's feet at (x, y, z), `scale` wide: its soft contact shadow
	// a block the host's gravity gun tore out (IN_TAKE_BLOCK): id = its held slot, uv[0..2] = side,
	// top, bottom, tint as WE_BLOCK's. The host draws it on its own physics body (x/y/z unused)
	public static final int WE_HELD_BLOCK = 7;

	// WorldEntity: offsets in it
	public static final long WORLD_ENTITY_KIND = 0x00; // WorldEntityKind
	public static final long WORLD_ENTITY_ID = 0x04; // MC entity id (stable while it exists)
	public static final long WORLD_ENTITY_X = 0x08; // MC coords (interpolated at MC's render time)
	public static final long WORLD_ENTITY_Y = 0x0C;
	public static final long WORLD_ENTITY_Z = 0x10;
	public static final long WORLD_ENTITY_YAW = 0x14; // MC degrees
	public static final long WORLD_ENTITY_PITCH = 0x18;
	public static final long WORLD_ENTITY_SCALE = 0x1C;
	public static final long WORLD_ENTITY_EXT = 0x20; // WE_CRACK: box size
	public static final long WORLD_ENTITY_UV = 0x2C; // atlas rects {u0, v0, u1, v1}
	public static final long WORLD_ENTITY_TINT = 0x5C; // RGBA8 multiplier for the top face (grass, leaves); 0 = none
	public static final int WORLD_ENTITY_BYTES = 0x60;

	// WorldEntities: offsets in it (in OFF_WORLD_ENTITIES)
	public static final long WE_SEQ = 0x00;
	public static final long WE_COUNT = 0x04;
	public static final long WE_HAS_SELECTION = 0x08; // draw an outline around the targeted block
	public static final long WE_SEL_MIN = 0x0C; // MC coords
	public static final long WE_SEL_MAX = 0x18;
	public static final long WE_RECORDS = 0x40;
	public static final int WE_BYTES = 0x3C40;

	// ---- host debug @0x22000 ------------------------------------------------------------------------
	// (#7) what Minecraft's debug screen (F3) shows about the host, a few times a second. Two
	// seqlocked parts, one per writer: client.dll's HostDebug at the region's start and server.dll's
	// HostDebugServer at HD_SERVER (what's under the crosshair: npc health isn't networked
	// to the client). Strings are UTF-8, NUL-terminated (truncated).
	public static final long HD_SERVER = 0x800; // from OFF_HOST_DEBUG
	public static final int HDS_TEXT_BYTES = 48; // HostDebugServer's strings
	public static final long RING_OUT_OF_STEP = 0xFFFFFFFFFFFFFFFFL; // HostDebug's four pendings while that ring's two indices disagree (~0)

	// HostDebugFlags
	public static final int HD_PUPPET = 1 << 0; // Minecraft drives the host's player
	public static final int HD_MINECRAFT_INPUT = 1 << 1; // keys and mouse go to Minecraft
	public static final int HD_MINECRAFT_HUD = 1 << 2; // Minecraft's overlay is shown

	// HostDebug: offsets in it (in OFF_HOST_DEBUG)
	public static final long HD_SEQ = 0x00;
	public static final long HD_FLAGS = 0x04; // HostDebugFlags
	public static final long HD_MAP = 0x08; // the host's map; empty: none loaded
	public static final int HD_MAP_BYTES = 64;
	public static final long HD_CHAPTER = 0x48; // the map's chapter ("9a"), from the game's cfg/chapter*.cfg; empty: none
	public static final int HD_CHAPTER_BYTES = 8;
	public static final long HD_CHAPTER_TITLE = 0x50; // the chapter's title in the player's language
	public static final int HD_CHAPTER_TITLE_BYTES = 64;
	public static final long HD_ORIGIN = 0x90; // the player's feet, host units (Source: z up)
	public static final long HD_ANGLES = 0x9C; // the player's view: pitch, yaw, roll (host degrees)
	public static final long HD_FPS = 0xA8; // the host's frames over the last second
	public static final long HD_WORST_FRAME_MS = 0xAC; // the longest of them
	public static final long HD_OVERLAY_MS = 0xB0; // what drawing Minecraft's overlay cost a frame, on average over them
	public static final long HD_SLOT = 0xB4; // the map's slot in Minecraft's world (1024 blocks along x each)
	public static final long HD_COLLISION_EPOCH = 0xB8; // as in HostState
	public static final long HD_INPUT_PENDING = 0xBC; // input ring entries Minecraft hasn't read yet
	public static final long HD_EVENT_PENDING = 0xC0; // event ring entries the host hasn't read yet
	public static final long HD_LIGHT_EMITTERS = 0xC4; // Minecraft's light-emitting blocks the host knows of
	public static final long HD_COLLISION_PENDING = 0xC8; // collision ring bytes Minecraft hasn't read yet
	public static final long HD_RENDER_PENDING = 0xD0; // render ring bytes the host hasn't read yet
	public static final long HD_LIGHTS = 0xD8; // lights made of those emitters around the player
	public static final long HD_SHADOWED_LIGHTS = 0xDC; // of those, the shadowed point lights (the rest light only characters)
	public static final long HD_GRID_Z = 0xE0; // the map's block grid: the source z of minecraft's y = 0 (whole units)
	public static final int HD_BYTES = 0xE8;

	// HostDebugServer: offsets in it (in OFF_HOST_DEBUG)
	public static final long HDS_SEQ = 0x00;
	public static final long HDS_ENTITY_COUNT = 0x04; // the host's edicts in use
	public static final long HDS_TARGET_INDEX = 0x08; // the entity under the crosshair: its entity index (0: it has none)
	public static final long HDS_HEALTH = 0x0C; // its health and maximum health
	public static final long HDS_MAX_HEALTH = 0x10;
	public static final long HDS_DISTANCE = 0x14; // from the player's eye, host units
	// how a character feels about the player: Source's Disposition_t (1 hate, 2 fear, 3 like,
	// 4 neutral); 0: not a character
	public static final long HDS_RELATION = 0x18;
	// Source's NPC_STATE (1 idle, 2 alert, 3 combat, 4 script, 5 play dead, 6 held by a barnacle,
	// 7 dead); 0: not an npc
	public static final long HDS_NPC_STATE = 0x1C;
	public static final long HDS_TARGET_CLASS = 0x20; // empty: nothing under the crosshair (the world doesn't count)
	public static final int HDS_TARGET_CLASS_BYTES = 48;
	public static final long HDS_TARGET_NAME = 0x50; // its map name; empty: none
	public static final int HDS_TARGET_NAME_BYTES = 48;
	public static final long HDS_SCHEDULE = 0x80; // what an npc is doing (its AI schedule)
	public static final int HDS_SCHEDULE_BYTES = 48;
	public static final int HDS_BYTES = 0xB0;

	// ---- weapon table @0x23000 ----------------------------------------------------------------------
	// (#12) the host's weapons the player owns, which Minecraft shows as items (McState::heldWeapon).
	// The host's inventory is the authority: Minecraft adds the items it lacks and removes the ones
	// the host no longer lists, and the host's player has out whichever weapon Minecraft's hand holds.
	public static final int WT_MAX_WEAPONS = 48; // Source's MAX_WEAPONS

	// WeaponId
	// Which weapon (Half-Life 2 and its episodes give the player these; Minecraft has one item each).
	public static final int HOST_WEAPON_NONE = 0;
	public static final int HOST_WEAPON_CROWBAR = 1; // weapon_crowbar
	public static final int HOST_WEAPON_PHYSCANNON = 2; // weapon_physcannon (the gravity gun, also supercharged)
	public static final int HOST_WEAPON_PISTOL = 3; // weapon_pistol
	public static final int HOST_WEAPON_357 = 4; // weapon_357
	public static final int HOST_WEAPON_SMG1 = 5; // weapon_smg1
	public static final int HOST_WEAPON_AR2 = 6; // weapon_ar2
	public static final int HOST_WEAPON_SHOTGUN = 7; // weapon_shotgun
	public static final int HOST_WEAPON_CROSSBOW = 8; // weapon_crossbow
	public static final int HOST_WEAPON_FRAG = 9; // weapon_frag
	public static final int HOST_WEAPON_RPG = 10; // weapon_rpg
	public static final int HOST_WEAPON_BUGBAIT = 11; // weapon_bugbait

	// WeaponTableFlags
	public static final int WT_LIVE = 1 << 0; // the host's player is in a map and alive: the list is its inventory
	public static final int WT_SUPPRESSED = 1 << 1; // the host keeps the weapons away (player_speedmod): none comes out

	// WeaponRecordFlags
	public static final int WT_R_SUPERCHARGED = 1 << 0; // the gravity gun, supercharged (the Citadel)

	// WeaponRecord: offsets in it
	public static final long WT_R_ID = 0x00; // WeaponId
	public static final long WT_R_CLIP = 0x04; // rounds in the clip; -1: no clip (it fires from the reserve, or uses no ammo)
	public static final long WT_R_MAX_CLIP = 0x08; // the clip's size; -1: no clip
	public static final long WT_R_AMMO = 0x0C; // primary rounds in reserve; -1: it uses no ammo (crowbar, gravity gun)
	public static final long WT_R_MAX_AMMO = 0x10; // the most primary rounds the player can carry
	public static final long WT_R_AMMO2 = 0x14; // secondary rounds (SMG grenades, AR2 balls); -1: none
	public static final long WT_R_MAX_AMMO2 = 0x18;
	public static final long WT_R_FLAGS = 0x1C; // WeaponRecordFlags
	public static final int WT_RECORD_BYTES = 0x20;

	// WeaponTable: offsets in it (in OFF_WEAPON_TABLE)
	public static final long WT_SEQ = 0x00;
	public static final long WT_FLAGS = 0x04; // WeaponTableFlags
	public static final long WT_COUNT = 0x08;
	public static final long WT_ACTIVE = 0x0C; // WeaponId the host's player has out right now (0: none)
	public static final long WT_RECORDS = 0x40;
	public static final int WT_BYTES = 0x640;

	// ---- mob table @0x24000 -------------------------------------------------------------------------
	// (#13) Minecraft's mobs near the player, which the host's characters see and fight: its monsters
	// and the player's pets (no animals or villagers), nearest first. Written once per Minecraft tick.
	public static final int MAX_MOBS = 256;
	// IN_HURT_MOB's attacker when the host's own player landed the hit (an actor id is never this).
	public static final int MOB_ATTACKER_PLAYER = 0xFFFFFFFF;

	// MobFlags
	public static final int MOB_HOSTILE = 1 << 0; // a monster: the host's enemies of monsters fight it
	public static final int MOB_PET = 1 << 1; // tamed by the player: the host's characters see it as the player's ally
	public static final int MOB_UNDEAD = 1 << 2; // zombies, skeletons, ...

	// MobRecord: offsets in it
	public static final long MR_ID = 0x00; // the Minecraft entity id, stable while the mob exists
	public static final long MR_FLAGS = 0x04; // MobFlags
	public static final long MR_X = 0x08; // feet, MC coords
	public static final long MR_Y = 0x0C;
	public static final long MR_Z = 0x10;
	public static final long MR_YAW = 0x14; // MC degrees
	public static final long MR_WIDTH = 0x18; // blocks
	public static final long MR_HEIGHT = 0x1C; // blocks
	public static final long MR_HEALTH = 0x20; // Minecraft points
	public static final long MR_MAX_HEALTH = 0x24;
	public static final int MOB_RECORD_BYTES = 0x30;

	// MobTable: offsets in it (in OFF_MOB_TABLE)
	public static final long MT_SEQ = 0x00;
	public static final long MT_COUNT = 0x04;
	public static final long MT_RECORDS = 0x40;
	public static final int MT_BYTES = 0x3040;

	// ---- water probes @0x29000 ----------------------------------------------------------------------
	// The host's water around Minecraft's boats and fishing bobbers, and its mobs and dropped items off
	// the player's WaterGrid, which that grid doesn't reach: a boat left behind, a bobber cast far out or
	// down into a canal, a zombie wading in one. Minecraft lists where they are (WaterProbeRequests: boats
	// and bobbers first, then mobs, then items, the nearest to the player first of each, at most
	// MAX_WATER_PROBES); client.dll probes a small grid of block columns
	// around each, the way it probes the WaterGrid, and answers in WaterProbes at WP_ANSWERS.
	// An answer's slot follows its request's, a frame or two behind; each is probed again when its
	// thing nears the edge of its grid or moves up or down, else a few times a second. A probe looks
	// for the surface from 3 blocks above its y down to WATER_PROBE_DEPTH below it: under that it
	// knows nothing, so Minecraft takes no water from it there.
	public static final long WP_ANSWERS = 0x100; // from OFF_WATER_PROBES
	public static final int MAX_WATER_PROBES = 12; // a boat waits for the probe chosen for it (HostWater)
	public static final int WATER_PROBE_SIZE = 8; // block columns along each side of a probe's grid
	public static final float WATER_PROBE_DEPTH = 6.0F; // blocks below a probe's y its search reaches

	// WaterProbeRequests: offsets in it (in OFF_WATER_PROBES)
	public static final long WPR_SEQ = 0x00;
	public static final long WPR_COUNT = 0x04;
	public static final long WPR_AT = 0x08; // MC coords: a grid centred on (x, z), probed around y
	public static final int WPR_BYTES = 0x98;

	// WaterProbe: offsets in it
	public static final long WP_ORIGIN_X = 0x00; // Minecraft block column of surface[0]
	public static final long WP_ORIGIN_Z = 0x04;
	public static final long WP_Y = 0x08; // the height it was probed around
	public static final long WP_SURFACE = 0x10; // [z * size + x]: MC y of the water surface; NO_WATER: none
	public static final int WATER_PROBE_BYTES = 0x110;

	// WaterProbes: offsets in it (in OFF_WATER_PROBES)
	public static final long WP_SEQ = 0x00;
	public static final long WP_COUNT = 0x04;
	public static final long WP_PROBES = 0x10;
	public static final int WP_BYTES = 0xCD0;

	// ---- collision ring @0x40000 --------------------------------------------------------------------
	// The host produces, MC consumes. Byte ring. Every message starts 8-byte aligned with {u32 type, u32 payloadBytes}.
	// A COL_PAD message means "skip to the start of the ring".
	public static final long CR_HEAD = 0x00; // u64 total bytes written
	public static final long CR_TAIL = 0x40; // u64 total bytes consumed
	public static final long CR_DATA = 0x80;
	public static final long CR_DATA_BYTES = 0x1FFFF80; // COLLISION_RING_BYTES - CR_DATA

	// ColType
	public static final int COL_PAD = 0;
	public static final int COL_CLEAR = 1; // payload: u32 epoch
	public static final int COL_REGION = 2; // payload: ColRegion + ColBlock[count]
	public static final int COL_TRIS = 3; // payload: ColRegion (count = triangles) + ColTri[count]; sent before COL_REGION

	// ColTriFlags
	public static final int TRI_STAIR_HELPER = 1 << 0; // an invisible stair ramp: walkable, never a wall
	public static final int TRI_SKY = 1 << 1; // a brush of the map's sky (its skybox ceiling): what's under it is out in the open

	// ColBlockFlags
	public static final int COL_BLOCK_SKY = 1 << 0; // all of it is the map's sky (TRI_SKY): no roof over what's under it

	// ColTri: offsets in it
	// Exact host collision triangle (MC space) for the player's smooth collider.
	public static final long COL_TRI_V = 0x00;
	public static final long COL_TRI_FLAGS = 0x24; // ColTriFlags
	public static final int COL_TRI_BYTES = 0x28;

	// ColMsgHeader: offsets in it
	public static final long COL_MSG_HEADER_TYPE = 0x00; // ColType
	public static final long COL_MSG_HEADER_PAYLOAD_BYTES = 0x04;
	public static final int COL_MSG_HEADER_BYTES = 0x08;

	// ColRegion: offsets in it
	// Replaces all host collision inside the inclusive block box [min, max].
	public static final long COL_REGION_MIN_X = 0x00;
	public static final long COL_REGION_MIN_Y = 0x04;
	public static final long COL_REGION_MIN_Z = 0x08;
	public static final long COL_REGION_MAX_X = 0x0C;
	public static final long COL_REGION_MAX_Y = 0x10;
	public static final long COL_REGION_MAX_Z = 0x14;
	public static final long COL_REGION_EPOCH = 0x18;
	public static final long COL_REGION_COUNT = 0x1C;
	public static final int COL_REGION_HEADER_BYTES = 0x20;

	// ColBlock: offsets in it
	// One block's worth of host collision as an 8x8x8 occupancy mask.
	// bits[y] bit (z * 8 + x) is sub-voxel (x, y, z), each 1/8 block, in MC axes.
	public static final long COL_BLOCK_X = 0x00;
	public static final long COL_BLOCK_Y = 0x04;
	public static final long COL_BLOCK_Z = 0x08;
	public static final long COL_BLOCK_FLAGS = 0x0C; // ColBlockFlags
	public static final long COL_BLOCK_BITS = 0x10;
	public static final int COL_BLOCK_BYTES = 0x50;

	// ---- render ring @0x7F2C000 ---------------------------------------------------------------------
	// MC produces, the host consumes. Byte ring like the collision ring. Minecraft ships its own block meshes
	// (built by Minecraft's block renderer: models, tint, AO, lighting) and its block atlas; the host draws them
	// in its own frame so blocks stay locked to the world and are hidden by the host's geometry.
	public static final long RR_HEAD = 0x00;
	public static final long RR_TAIL = 0x40;
	public static final long RR_DATA = 0x80;
	public static final long RR_DATA_BYTES = 0x3FFFF80; // RENDER_RING_BYTES - RR_DATA

	// RenType
	public static final int REN_PAD = 0;
	public static final int REN_ATLAS = 1; // RenAtlas + RGBA8 pixels (w * h * 4), top row first
	public static final int REN_SECTION = 2; // RenSection + RenVertex[vertexCount] (triangle list); 0 vertices = remove
	public static final int REN_CLEAR_ALL = 3; // drop every section (world change)
	public static final int REN_TEXTURE = 4; // RenTexture + RGBA8 pixels: an entity texture (player skin, armour, ...)
	// RenAvatar + RenBatch[batchCount] + RenVertex[vertexCount]: the player's
	// model this frame; 0 batches = not shown (first person)
	public static final int REN_AVATAR = 5;
	// RenScene + RenBatch[batchCount] + RenVertex[vertexCount]: every other
	// entity and all particles this frame, relative to RenScene's origin
	public static final int REN_SCENE = 6;
	public static final int REN_ATLAS_REGION = 7; // RenAtlasRegion + RGBA8 pixels: an animated sprite's current frame
	// RenLights + RenLight[count]: a section's light-emitting blocks (sent
	// after its REN_SECTION; 0 = none)
	public static final int REN_LIGHTS = 8;
	// RenAvatar + RenBatch[] + RenVertex[]: the player's body standing still,
	// relative to the feet and facing +Z, split into its parts (RenBatch
	// flags bits 8-11: RagdollPart). Sent about once a second while alive,
	// for a host that hangs the parts on a ragdoll when the player dies.
	public static final int REN_RAGDOLL = 9;
	// RenSolids + two 512-byte bitsets (bit x + 16z + 256y): which blocks of a
	// section the host's characters collide with, then which of those the host's gravity gun
	// may tear out (IN_TAKE_BLOCK: whole cubes without a block entity, softer than obsidian).
	// Sent after its REN_SECTION; count 0: none, and no bitsets follow
	public static final int REN_SOLIDS = 10;

	// RagdollPart
	public static final int PART_NONE = 0;
	public static final int PART_HEAD = 1;
	public static final int PART_BODY = 2;
	public static final int PART_RIGHT_ARM = 3;
	public static final int PART_LEFT_ARM = 4;
	public static final int PART_RIGHT_LEG = 5;
	public static final int PART_LEFT_LEG = 6;
	public static final int PART_COUNT = 7;

	// LightKind
	public static final int LIGHT_STEADY = 0;
	public static final int LIGHT_FLAME = 1; // torches, fire, campfires, candles: flicker
	public static final int LIGHT_LAVA = 2; // lava, magma: a slow glow

	// BlockHazard
	public static final int HAZARD_NONE = 0;
	public static final int HAZARD_FIRE = 1; // fire, soul fire, campfires: burns what stands in it
	public static final int HAZARD_LAVA = 2; // lava: burns hard
	public static final int HAZARD_MAGMA = 3; // magma block: hurts what stands on top of it

	// RenSolids: offsets in it
	public static final long REN_SOLIDS_SX = 0x00; // section coords, as in RenSection
	public static final long REN_SOLIDS_SY = 0x04;
	public static final long REN_SOLIDS_SZ = 0x08;
	public static final long REN_SOLIDS_COUNT = 0x0C; // solid blocks (0: none, and no bitset follows)
	public static final int REN_SOLIDS_BYTES = 0x10;

	// RenLights: offsets in it
	public static final long REN_LIGHTS_SX = 0x00; // section coords, as in RenSection
	public static final long REN_LIGHTS_SY = 0x04;
	public static final long REN_LIGHTS_SZ = 0x08;
	public static final long REN_LIGHTS_COUNT = 0x0C;
	public static final int REN_LIGHTS_BYTES = 0x10;

	// RenLight: offsets in it
	public static final long REN_LIGHT_X = 0x00; // block within the section
	public static final long REN_LIGHT_Y = 0x01;
	public static final long REN_LIGHT_Z = 0x02;
	public static final long REN_LIGHT_LEVEL = 0x03; // Minecraft light emission, 1-15
	public static final long REN_LIGHT_COLOR = 0x04; // RGB8 (r low byte); top byte: LightKind in bits 0-3, BlockHazard in 4-7
	public static final int REN_LIGHT_BYTES = 0x08;

	// RenAtlasRegion: offsets in it
	public static final long REN_ATLAS_REGION_X = 0x00; // pixels in the combined atlas (REN_ATLAS)
	public static final long REN_ATLAS_REGION_Y = 0x04;
	public static final long REN_ATLAS_REGION_WIDTH = 0x08;
	public static final long REN_ATLAS_REGION_HEIGHT = 0x0C;
	public static final int REN_ATLAS_REGION_BYTES = 0x10;

	// RenScene: offsets in it
	public static final long REN_SCENE_ORIGIN_X = 0x00; // MC block the positions are relative to
	public static final long REN_SCENE_ORIGIN_Y = 0x08;
	public static final long REN_SCENE_ORIGIN_Z = 0x10;
	public static final long REN_SCENE_BATCH_COUNT = 0x18;
	public static final long REN_SCENE_VERTEX_COUNT = 0x1C;
	public static final int REN_SCENE_BYTES = 0x20;

	// RenTexture: offsets in it
	public static final long REN_TEXTURE_ID = 0x00; // 1+, referenced by RenBatch::texture
	public static final long REN_TEXTURE_WIDTH = 0x04;
	public static final long REN_TEXTURE_HEIGHT = 0x08;
	public static final int REN_TEXTURE_BYTES = 0x10;

	// RenAvatar: offsets in it
	// The player as Minecraft's own entity renderer draws it (skin, armour, held items, cape),
	// posed and animated, with positions in blocks relative to the player's feet: the host puts
	// it at its own interpolated feet position, the one its camera follows.
	public static final long REN_AVATAR_BATCH_COUNT = 0x00;
	public static final long REN_AVATAR_VERTEX_COUNT = 0x04;
	public static final int REN_AVATAR_BYTES = 0x08;

	// RenBatch: offsets in it
	public static final long REN_BATCH_TEXTURE = 0x00; // 0: the block/item atlas, else a RenTexture id
	public static final long REN_BATCH_FIRST = 0x04; // first vertex
	public static final long REN_BATCH_COUNT = 0x08; // vertices (multiple of 3)
	public static final long REN_BATCH_FLAGS = 0x0C; // bit0: translucent (blended, after the solid pass)
	public static final int REN_BATCH_BYTES = 0x10;

	// RenAtlas: offsets in it
	public static final long REN_ATLAS_WIDTH = 0x00;
	public static final long REN_ATLAS_HEIGHT = 0x04;
	public static final int REN_ATLAS_BYTES = 0x08;

	// RenSection: offsets in it
	public static final long REN_SECTION_SX = 0x00; // section coords (16-block cubes)
	public static final long REN_SECTION_SY = 0x04;
	public static final long REN_SECTION_SZ = 0x08;
	public static final long REN_SECTION_VERTEX_COUNT = 0x0C; // multiple of 3
	public static final int REN_SECTION_BYTES = 0x10;

	// RenVertex: offsets in it
	public static final long REN_VERTEX_X = 0x00; // MC coords relative to the section origin (sx*16, sy*16, sz*16)
	public static final long REN_VERTEX_Y = 0x04;
	public static final long REN_VERTEX_Z = 0x08;
	public static final long REN_VERTEX_U = 0x0C; // atlas UV
	public static final long REN_VERTEX_V = 0x10;
	public static final long REN_VERTEX_COLOR = 0x14; // RGBA8 (tint * ambient occlusion; Minecraft's fixed face shading is left out)
	public static final long REN_VERTEX_LIGHT = 0x18; // low byte: block light 0-15, next byte: sky light 0-15
	// bit0: cutout (alpha test), bit1: translucent,
	// bits 4-6: face normal as MC Direction ordinal + 1 (0 = none: lit without a normal)
	public static final long REN_VERTEX_FLAGS = 0x1C;
	public static final int REN_VERTEX_BYTES = 0x20;
}
