package dev.halfcraft.link;

import static dev.halfcraft.link.Proto.*;
import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.MemorySegment;
import java.nio.charset.StandardCharsets;
import org.jspecify.annotations.Nullable;

/**
 * The structs Minecraft reads or writes whole: a class to extend, or a record, each with its read and write at
 * Proto.java's offsets. Generated by tools/build/protocol.py from protocol/schema/*.toml (a struct's java_class):
 * change the schema and run make proto, never this file. A seqlock's seq and a ring's indices are the callers'.
 */
public final class ProtoStructs {
	private ProtoStructs() {
	}

	// HostState: read, written and copied whole (in OFF_HOST_STATE)
	public static class HostState {
		public int flags; // HostFlags
		public int worldId; // the host's map (a hash of its name); never 0 in game
		public int collisionEpoch; // bumps on every level load; MC drops all collision data
		public double posX; // the host player's feet, MC coords
		public double posY;
		public double posZ;
		public float yaw; // authoritative look (MC degrees)
		public float pitch;
		public int teleportSeq; // MC teleports its player to pos when this changes
		public int viewportW;
		public int viewportH;
		public float gameHour;
		public float seatYaw; // the way the vehicle's seat faces (MC degrees), with HOST_SEATED
		public float speedFactor; // how fast source lets its player move (player_speedmod): 1 normal, 0.5 half speed
		// minecraft draws its overlay at the viewport's size over this (hc_overlay_scale), a gui scale it
		// was given divided alike, and the host scales it back up pixel for pixel. 0 (an older host): 1
		public int overlayDivisor;

		public void read(MemorySegment s, long at) {
			this.flags = s.get(JAVA_INT, at + HS_FLAGS);
			this.worldId = s.get(JAVA_INT, at + HS_WORLD_ID);
			this.collisionEpoch = s.get(JAVA_INT, at + HS_COLLISION_EPOCH);
			this.posX = s.get(JAVA_DOUBLE, at + HS_POS_X);
			this.posY = s.get(JAVA_DOUBLE, at + HS_POS_Y);
			this.posZ = s.get(JAVA_DOUBLE, at + HS_POS_Z);
			this.yaw = s.get(JAVA_FLOAT, at + HS_YAW);
			this.pitch = s.get(JAVA_FLOAT, at + HS_PITCH);
			this.teleportSeq = s.get(JAVA_INT, at + HS_TELEPORT_SEQ);
			this.viewportW = s.get(JAVA_INT, at + HS_VIEWPORT_W);
			this.viewportH = s.get(JAVA_INT, at + HS_VIEWPORT_H);
			this.gameHour = s.get(JAVA_FLOAT, at + HS_GAME_HOUR);
			this.seatYaw = s.get(JAVA_FLOAT, at + HS_SEAT_YAW);
			this.speedFactor = s.get(JAVA_FLOAT, at + HS_SPEED_FACTOR);
			this.overlayDivisor = s.get(JAVA_INT, at + HS_OVERLAY_DIVISOR);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + HS_FLAGS, this.flags);
			s.set(JAVA_INT, at + HS_WORLD_ID, this.worldId);
			s.set(JAVA_INT, at + HS_COLLISION_EPOCH, this.collisionEpoch);
			s.set(JAVA_DOUBLE, at + HS_POS_X, this.posX);
			s.set(JAVA_DOUBLE, at + HS_POS_Y, this.posY);
			s.set(JAVA_DOUBLE, at + HS_POS_Z, this.posZ);
			s.set(JAVA_FLOAT, at + HS_YAW, this.yaw);
			s.set(JAVA_FLOAT, at + HS_PITCH, this.pitch);
			s.set(JAVA_INT, at + HS_TELEPORT_SEQ, this.teleportSeq);
			s.set(JAVA_INT, at + HS_VIEWPORT_W, this.viewportW);
			s.set(JAVA_INT, at + HS_VIEWPORT_H, this.viewportH);
			s.set(JAVA_FLOAT, at + HS_GAME_HOUR, this.gameHour);
			s.set(JAVA_FLOAT, at + HS_SEAT_YAW, this.seatYaw);
			s.set(JAVA_FLOAT, at + HS_SPEED_FACTOR, this.speedFactor);
			s.set(JAVA_INT, at + HS_OVERLAY_DIVISOR, this.overlayDivisor);
			s.asSlice(at + 0x4C, 4).fill((byte) 0); // overlayPad
		}

		public void copyFrom(HostState other) {
			this.flags = other.flags;
			this.worldId = other.worldId;
			this.collisionEpoch = other.collisionEpoch;
			this.posX = other.posX;
			this.posY = other.posY;
			this.posZ = other.posZ;
			this.yaw = other.yaw;
			this.pitch = other.pitch;
			this.teleportSeq = other.teleportSeq;
			this.viewportW = other.viewportW;
			this.viewportH = other.viewportH;
			this.gameHour = other.gameHour;
			this.seatYaw = other.seatYaw;
			this.speedFactor = other.speedFactor;
			this.overlayDivisor = other.overlayDivisor;
		}
	}

	// WaterGrid: read, written and copied whole (in OFF_WATER_GRID)
	// The host's water around the player, for Minecraft to treat as its own water: swimming,
	// floating, drowning. Seqlock like HostState.
	public static class WaterGrid {
		public int originX; // Minecraft block column of surface[0]
		public int originZ;
		public int worldId; // as in HostState
		public final float[] surface = new float[256]; // [z * size + x]: MC y of the water surface; NO_WATER: none

		public void read(MemorySegment s, long at) {
			this.originX = s.get(JAVA_INT, at + WG_ORIGIN_X);
			this.originZ = s.get(JAVA_INT, at + WG_ORIGIN_Z);
			this.worldId = s.get(JAVA_INT, at + WG_WORLD_ID);
			MemorySegment.copy(s, JAVA_FLOAT, at + WG_SURFACE, this.surface, 0, 256);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + WG_ORIGIN_X, this.originX);
			s.set(JAVA_INT, at + WG_ORIGIN_Z, this.originZ);
			s.set(JAVA_INT, at + WG_WORLD_ID, this.worldId);
			putFloats(s, at + WG_SURFACE, this.surface, 256);
		}

		public void copyFrom(WaterGrid other) {
			this.originX = other.originX;
			this.originZ = other.originZ;
			this.worldId = other.worldId;
			System.arraycopy(other.surface, 0, this.surface, 0, 256);
		}
	}

	// McState: read, written and copied whole (in OFF_MC_STATE)
	public static class McState {
		public int flags; // McFlags
		public double x; // interpolated feet position (MC coords)
		public double y;
		public double z;
		public float yaw; // MC rotation (degrees); asleep in first person its camera's, along the bed
		public float pitch;
		public float eyeHeight; // blocks above feet
		public float sensitivity; // MC mouse sensitivity option (0..1)
		public int teleportAck; // last HostState::teleportSeq applied
		public int guiScale;
		public long frameCounter;
		public float fovDeg; // effective vertical FOV (includes sprint / fluid modifiers)
		public float bobPhase; // MC walk-bob phase (interpolated walk distance); 0 if bobbing is off
		public float bobAmount; // MC walk-bob amplitude
		public double eyeX; // MC camera position (interpolated, includes sneak eye lerp)
		public double eyeY;
		public double eyeZ;
		// Raw 20 Hz physics ticks, so the host can interpolate on its own frame clock exactly like
		// Minecraft's renderer does with partial ticks (no judder from the two games' frame phase).
		// tickQpc: QueryPerformanceCounter at the (remainder-corrected) tick
		public long tickQpc;
		public double prevX; // feet at the previous tick
		public double prevY;
		public double prevZ;
		public double curX; // feet at the latest tick
		public double curY;
		public double curZ;
		public float tickEyeO; // Camera's smoothed eye height, previous/latest tick
		public float tickEye;
		public float walkDistO; // walk-bob phase inputs
		public float walkDist;
		public float bobO; // walk-bob amplitude inputs
		public float bob;
		public float tickMs; // milliseconds per tick (50 unless /tick rate changed)
		// Minecraft's camera (F5): 0 first person, 1 third person behind, 2 third person in front
		// (looking back at the player). cameraDistance is how far Minecraft's camera sits from
		// the eye, after its own zoom collision (Minecraft blocks and the host's triangles).
		public int cameraMode;
		public float cameraDistance;
		// The player's health and absorption (golden hearts), in Minecraft points (20 = 10 hearts).
		public float health;
		public float maxHealth;
		public float absorption;
		// (#12) the host's weapon the player holds as a Minecraft item (see WeaponTable); 0: none
		public int heldWeapon;
		// Bumps each time Minecraft moved its player by itself (an ender pearl, chorus fruit, /tp; not the
		// host's own teleports), in the same tick as curX/Y/Z: the host takes the jump that follows wherever
		// the player fits, and resyncs Minecraft where it doesn't.
		public int teleportCount;

		public void read(MemorySegment s, long at) {
			this.flags = s.get(JAVA_INT, at + MS_FLAGS);
			this.x = s.get(JAVA_DOUBLE, at + MS_X);
			this.y = s.get(JAVA_DOUBLE, at + MS_Y);
			this.z = s.get(JAVA_DOUBLE, at + MS_Z);
			this.yaw = s.get(JAVA_FLOAT, at + MS_YAW);
			this.pitch = s.get(JAVA_FLOAT, at + MS_PITCH);
			this.eyeHeight = s.get(JAVA_FLOAT, at + MS_EYE_HEIGHT);
			this.sensitivity = s.get(JAVA_FLOAT, at + MS_SENSITIVITY);
			this.teleportAck = s.get(JAVA_INT, at + MS_TELEPORT_ACK);
			this.guiScale = s.get(JAVA_INT, at + MS_GUI_SCALE);
			this.frameCounter = s.get(JAVA_LONG, at + MS_FRAME_COUNTER);
			this.fovDeg = s.get(JAVA_FLOAT, at + MS_FOV);
			this.bobPhase = s.get(JAVA_FLOAT, at + MS_BOB_PHASE);
			this.bobAmount = s.get(JAVA_FLOAT, at + MS_BOB_AMOUNT);
			this.eyeX = s.get(JAVA_DOUBLE, at + MS_EYE_X);
			this.eyeY = s.get(JAVA_DOUBLE, at + MS_EYE_Y);
			this.eyeZ = s.get(JAVA_DOUBLE, at + MS_EYE_Z);
			this.tickQpc = s.get(JAVA_LONG, at + MS_TICK_QPC);
			this.prevX = s.get(JAVA_DOUBLE, at + MS_PREV_X);
			this.prevY = s.get(JAVA_DOUBLE, at + MS_PREV_Y);
			this.prevZ = s.get(JAVA_DOUBLE, at + MS_PREV_Z);
			this.curX = s.get(JAVA_DOUBLE, at + MS_CUR_X);
			this.curY = s.get(JAVA_DOUBLE, at + MS_CUR_Y);
			this.curZ = s.get(JAVA_DOUBLE, at + MS_CUR_Z);
			this.tickEyeO = s.get(JAVA_FLOAT, at + MS_EYE_HEIGHT_O);
			this.tickEye = s.get(JAVA_FLOAT, at + MS_EYE_HEIGHT_T);
			this.walkDistO = s.get(JAVA_FLOAT, at + MS_WALK_O);
			this.walkDist = s.get(JAVA_FLOAT, at + MS_WALK);
			this.bobO = s.get(JAVA_FLOAT, at + MS_BOB_O);
			this.bob = s.get(JAVA_FLOAT, at + MS_BOB);
			this.tickMs = s.get(JAVA_FLOAT, at + MS_TICK_MS);
			this.cameraMode = s.get(JAVA_INT, at + MS_CAMERA_MODE);
			this.cameraDistance = s.get(JAVA_FLOAT, at + MS_CAMERA_DISTANCE);
			this.health = s.get(JAVA_FLOAT, at + MS_HEALTH);
			this.maxHealth = s.get(JAVA_FLOAT, at + MS_MAX_HEALTH);
			this.absorption = s.get(JAVA_FLOAT, at + MS_ABSORPTION);
			this.heldWeapon = s.get(JAVA_INT, at + MS_HELD_WEAPON);
			this.teleportCount = s.get(JAVA_INT, at + MS_TELEPORT_COUNT);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + MS_FLAGS, this.flags);
			s.set(JAVA_DOUBLE, at + MS_X, this.x);
			s.set(JAVA_DOUBLE, at + MS_Y, this.y);
			s.set(JAVA_DOUBLE, at + MS_Z, this.z);
			s.set(JAVA_FLOAT, at + MS_YAW, this.yaw);
			s.set(JAVA_FLOAT, at + MS_PITCH, this.pitch);
			s.set(JAVA_FLOAT, at + MS_EYE_HEIGHT, this.eyeHeight);
			s.set(JAVA_FLOAT, at + MS_SENSITIVITY, this.sensitivity);
			s.set(JAVA_INT, at + MS_TELEPORT_ACK, this.teleportAck);
			s.set(JAVA_INT, at + MS_GUI_SCALE, this.guiScale);
			s.set(JAVA_LONG, at + MS_FRAME_COUNTER, this.frameCounter);
			s.set(JAVA_FLOAT, at + MS_FOV, this.fovDeg);
			s.set(JAVA_FLOAT, at + MS_BOB_PHASE, this.bobPhase);
			s.set(JAVA_FLOAT, at + MS_BOB_AMOUNT, this.bobAmount);
			s.asSlice(at + 0x4C, 4).fill((byte) 0); // pad4C
			s.set(JAVA_DOUBLE, at + MS_EYE_X, this.eyeX);
			s.set(JAVA_DOUBLE, at + MS_EYE_Y, this.eyeY);
			s.set(JAVA_DOUBLE, at + MS_EYE_Z, this.eyeZ);
			s.set(JAVA_LONG, at + MS_TICK_QPC, this.tickQpc);
			s.set(JAVA_DOUBLE, at + MS_PREV_X, this.prevX);
			s.set(JAVA_DOUBLE, at + MS_PREV_Y, this.prevY);
			s.set(JAVA_DOUBLE, at + MS_PREV_Z, this.prevZ);
			s.set(JAVA_DOUBLE, at + MS_CUR_X, this.curX);
			s.set(JAVA_DOUBLE, at + MS_CUR_Y, this.curY);
			s.set(JAVA_DOUBLE, at + MS_CUR_Z, this.curZ);
			s.set(JAVA_FLOAT, at + MS_EYE_HEIGHT_O, this.tickEyeO);
			s.set(JAVA_FLOAT, at + MS_EYE_HEIGHT_T, this.tickEye);
			s.set(JAVA_FLOAT, at + MS_WALK_O, this.walkDistO);
			s.set(JAVA_FLOAT, at + MS_WALK, this.walkDist);
			s.set(JAVA_FLOAT, at + MS_BOB_O, this.bobO);
			s.set(JAVA_FLOAT, at + MS_BOB, this.bob);
			s.set(JAVA_FLOAT, at + MS_TICK_MS, this.tickMs);
			s.asSlice(at + 0xBC, 4).fill((byte) 0); // tickPad
			s.set(JAVA_INT, at + MS_CAMERA_MODE, this.cameraMode);
			s.set(JAVA_FLOAT, at + MS_CAMERA_DISTANCE, this.cameraDistance);
			s.set(JAVA_FLOAT, at + MS_HEALTH, this.health);
			s.set(JAVA_FLOAT, at + MS_MAX_HEALTH, this.maxHealth);
			s.set(JAVA_FLOAT, at + MS_ABSORPTION, this.absorption);
			s.asSlice(at + 0xD4, 4).fill((byte) 0); // healthPad
			s.set(JAVA_INT, at + MS_HELD_WEAPON, this.heldWeapon);
			s.asSlice(at + 0xDC, 4).fill((byte) 0); // heldWeaponPad
			s.set(JAVA_INT, at + MS_TELEPORT_COUNT, this.teleportCount);
			s.asSlice(at + 0xE4, 12).fill((byte) 0); // teleportPad
		}

		public void copyFrom(McState other) {
			this.flags = other.flags;
			this.x = other.x;
			this.y = other.y;
			this.z = other.z;
			this.yaw = other.yaw;
			this.pitch = other.pitch;
			this.eyeHeight = other.eyeHeight;
			this.sensitivity = other.sensitivity;
			this.teleportAck = other.teleportAck;
			this.guiScale = other.guiScale;
			this.frameCounter = other.frameCounter;
			this.fovDeg = other.fovDeg;
			this.bobPhase = other.bobPhase;
			this.bobAmount = other.bobAmount;
			this.eyeX = other.eyeX;
			this.eyeY = other.eyeY;
			this.eyeZ = other.eyeZ;
			this.tickQpc = other.tickQpc;
			this.prevX = other.prevX;
			this.prevY = other.prevY;
			this.prevZ = other.prevZ;
			this.curX = other.curX;
			this.curY = other.curY;
			this.curZ = other.curZ;
			this.tickEyeO = other.tickEyeO;
			this.tickEye = other.tickEye;
			this.walkDistO = other.walkDistO;
			this.walkDist = other.walkDist;
			this.bobO = other.bobO;
			this.bob = other.bob;
			this.tickMs = other.tickMs;
			this.cameraMode = other.cameraMode;
			this.cameraDistance = other.cameraDistance;
			this.health = other.health;
			this.maxHealth = other.maxHealth;
			this.absorption = other.absorption;
			this.heldWeapon = other.heldWeapon;
			this.teleportCount = other.teleportCount;
		}
	}

	// OverlaySlotHdr: read and written whole (in OFF_OVERLAY_SLOT_HDR)
	//   flags: bit0: rows are bottom-up
	public record OverlaySlotHdr(int width, int height, int flags, long frameId) {
		public static OverlaySlotHdr read(MemorySegment s, long at) {
			int width = s.get(JAVA_INT, at + SH_WIDTH);
			int height = s.get(JAVA_INT, at + SH_HEIGHT);
			int flags = s.get(JAVA_INT, at + SH_FLAGS);
			long frameId = s.get(JAVA_LONG, at + SH_FRAME_ID);
			return new OverlaySlotHdr(width, height, flags, frameId);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + SH_WIDTH, this.width);
			s.set(JAVA_INT, at + SH_HEIGHT, this.height);
			s.set(JAVA_INT, at + SH_FLAGS, this.flags);
			s.asSlice(at + 0x0C, 4).fill((byte) 0); // pad
			s.set(JAVA_LONG, at + SH_FRAME_ID, this.frameId);
			s.asSlice(at + 0x18, 40).fill((byte) 0); // reserved
		}
	}

	// InputEvent: read and written whole
	//   type: InputType
	public record InputEvent(int type, int code, int a, int b, int c) {
		public static InputEvent read(MemorySegment s, long at) {
			int type = Short.toUnsignedInt(s.get(JAVA_SHORT, at + INPUT_EVENT_TYPE));
			int code = Short.toUnsignedInt(s.get(JAVA_SHORT, at + INPUT_EVENT_CODE));
			int a = s.get(JAVA_INT, at + INPUT_EVENT_A);
			int b = s.get(JAVA_INT, at + INPUT_EVENT_B);
			int c = s.get(JAVA_INT, at + INPUT_EVENT_C);
			return new InputEvent(type, code, a, b, c);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_SHORT, at + INPUT_EVENT_TYPE, (short) this.type);
			s.set(JAVA_SHORT, at + INPUT_EVENT_CODE, (short) this.code);
			s.set(JAVA_INT, at + INPUT_EVENT_A, this.a);
			s.set(JAVA_INT, at + INPUT_EVENT_B, this.b);
			s.set(JAVA_INT, at + INPUT_EVENT_C, this.c);
		}
	}

	// ActorRecord: read and written whole
	//   id: the host's handle for it, stable while it exists
	//   flags: ActorFlags
	//   x: feet, MC coords
	//   yaw: MC degrees
	//   width: blocks
	//   height: blocks
	//   healthFrac: 0..1
	//   name: display name, UTF-8, NUL-terminated (truncated)
	public record ActorRecord(int id, int flags, float x, float y, float z, float yaw, float width, float height, float healthFrac, int level, String name) implements HostLink.Actor {
		public static ActorRecord read(MemorySegment s, long at) {
			int id = s.get(JAVA_INT, at + ACTOR_RECORD_ID);
			int flags = s.get(JAVA_INT, at + ACTOR_RECORD_FLAGS);
			float x = s.get(JAVA_FLOAT, at + ACTOR_RECORD_X);
			float y = s.get(JAVA_FLOAT, at + ACTOR_RECORD_Y);
			float z = s.get(JAVA_FLOAT, at + ACTOR_RECORD_Z);
			float yaw = s.get(JAVA_FLOAT, at + ACTOR_RECORD_YAW);
			float width = s.get(JAVA_FLOAT, at + ACTOR_RECORD_WIDTH);
			float height = s.get(JAVA_FLOAT, at + ACTOR_RECORD_HEIGHT);
			float healthFrac = s.get(JAVA_FLOAT, at + ACTOR_RECORD_HEALTH_FRAC);
			int level = Short.toUnsignedInt(s.get(JAVA_SHORT, at + ACTOR_RECORD_LEVEL));
			String name = text(s, at + ACTOR_RECORD_NAME, 24);
			return new ActorRecord(id, flags, x, y, z, yaw, width, height, healthFrac, level, name);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + ACTOR_RECORD_ID, this.id);
			s.set(JAVA_INT, at + ACTOR_RECORD_FLAGS, this.flags);
			s.set(JAVA_FLOAT, at + ACTOR_RECORD_X, this.x);
			s.set(JAVA_FLOAT, at + ACTOR_RECORD_Y, this.y);
			s.set(JAVA_FLOAT, at + ACTOR_RECORD_Z, this.z);
			s.set(JAVA_FLOAT, at + ACTOR_RECORD_YAW, this.yaw);
			s.set(JAVA_FLOAT, at + ACTOR_RECORD_WIDTH, this.width);
			s.set(JAVA_FLOAT, at + ACTOR_RECORD_HEIGHT, this.height);
			s.set(JAVA_FLOAT, at + ACTOR_RECORD_HEALTH_FRAC, this.healthFrac);
			s.set(JAVA_SHORT, at + ACTOR_RECORD_LEVEL, (short) this.level);
			s.asSlice(at + 0x26, 2).fill((byte) 0); // pad
			putText(s, at + ACTOR_RECORD_NAME, 24, this.name);
		}
	}

	// McEvent: read and written whole
	//   type: McEventType
	//   weapon: HitWeapon for EV_HIT_ACTOR
	//   attackerId: (#13) EV_HIT_ACTOR: the Minecraft entity id of the mob that landed it; 0: the player. EV_EXPLOSION: the mob that set it off
	public record McEvent(int type, int actorId, float a, float b, float c, float d, int flags, int weapon, int attackerId) {
		public static McEvent read(MemorySegment s, long at) {
			int type = s.get(JAVA_INT, at + MC_EVENT_TYPE);
			int actorId = s.get(JAVA_INT, at + MC_EVENT_ACTOR_ID);
			float a = s.get(JAVA_FLOAT, at + MC_EVENT_A);
			float b = s.get(JAVA_FLOAT, at + MC_EVENT_B);
			float c = s.get(JAVA_FLOAT, at + MC_EVENT_C);
			float d = s.get(JAVA_FLOAT, at + MC_EVENT_D);
			int flags = s.get(JAVA_INT, at + MC_EVENT_FLAGS);
			int weapon = s.get(JAVA_INT, at + MC_EVENT_WEAPON);
			int attackerId = s.get(JAVA_INT, at + MC_EVENT_ATTACKER_ID);
			return new McEvent(type, actorId, a, b, c, d, flags, weapon, attackerId);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + MC_EVENT_TYPE, this.type);
			s.set(JAVA_INT, at + MC_EVENT_ACTOR_ID, this.actorId);
			s.set(JAVA_FLOAT, at + MC_EVENT_A, this.a);
			s.set(JAVA_FLOAT, at + MC_EVENT_B, this.b);
			s.set(JAVA_FLOAT, at + MC_EVENT_C, this.c);
			s.set(JAVA_FLOAT, at + MC_EVENT_D, this.d);
			s.set(JAVA_INT, at + MC_EVENT_FLAGS, this.flags);
			s.set(JAVA_INT, at + MC_EVENT_WEAPON, this.weapon);
			s.set(JAVA_INT, at + MC_EVENT_ATTACKER_ID, this.attackerId);
			s.asSlice(at + 0x24, 12).fill((byte) 0); // reserved
		}
	}

	// WorldEntity: read and written whole
	//   kind: WorldEntityKind
	//   id: MC entity id (stable while it exists)
	//   x: MC coords (interpolated at MC's render time)
	//   yaw: MC degrees
	//   ext: WE_CRACK: box size
	//   uv: atlas rects {u0, v0, u1, v1}
	//   tint: RGBA8 multiplier for the top face (grass, leaves); 0 = none
	public record WorldEntity(int kind, int id, float x, float y, float z, float yaw, float pitch, float scale, float[] ext, float[] uv, int tint) {
		public static WorldEntity read(MemorySegment s, long at) {
			int kind = s.get(JAVA_INT, at + WORLD_ENTITY_KIND);
			int id = s.get(JAVA_INT, at + WORLD_ENTITY_ID);
			float x = s.get(JAVA_FLOAT, at + WORLD_ENTITY_X);
			float y = s.get(JAVA_FLOAT, at + WORLD_ENTITY_Y);
			float z = s.get(JAVA_FLOAT, at + WORLD_ENTITY_Z);
			float yaw = s.get(JAVA_FLOAT, at + WORLD_ENTITY_YAW);
			float pitch = s.get(JAVA_FLOAT, at + WORLD_ENTITY_PITCH);
			float scale = s.get(JAVA_FLOAT, at + WORLD_ENTITY_SCALE);
			float[] ext = floats(s, at + WORLD_ENTITY_EXT, 3);
			float[] uv = floats(s, at + WORLD_ENTITY_UV, 12);
			int tint = s.get(JAVA_INT, at + WORLD_ENTITY_TINT);
			return new WorldEntity(kind, id, x, y, z, yaw, pitch, scale, ext, uv, tint);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + WORLD_ENTITY_KIND, this.kind);
			s.set(JAVA_INT, at + WORLD_ENTITY_ID, this.id);
			s.set(JAVA_FLOAT, at + WORLD_ENTITY_X, this.x);
			s.set(JAVA_FLOAT, at + WORLD_ENTITY_Y, this.y);
			s.set(JAVA_FLOAT, at + WORLD_ENTITY_Z, this.z);
			s.set(JAVA_FLOAT, at + WORLD_ENTITY_YAW, this.yaw);
			s.set(JAVA_FLOAT, at + WORLD_ENTITY_PITCH, this.pitch);
			s.set(JAVA_FLOAT, at + WORLD_ENTITY_SCALE, this.scale);
			putFloats(s, at + WORLD_ENTITY_EXT, this.ext, 3);
			putFloats(s, at + WORLD_ENTITY_UV, this.uv, 12);
			s.set(JAVA_INT, at + WORLD_ENTITY_TINT, this.tint);
		}
	}

	// HostDebug: read, written and copied whole (in OFF_HOST_DEBUG)
	public static class HostDebug {
		public int flags; // HostDebugFlags
		public String map = ""; // the host's map; empty: none loaded
		public String chapter = ""; // the map's chapter ("9a"), from the game's cfg/chapter*.cfg; empty: none
		public String chapterTitle = ""; // the chapter's title in the player's language
		public final float[] origin = new float[3]; // the player's feet, host units (Source: z up)
		public final float[] angles = new float[3]; // the player's view: pitch, yaw, roll (host degrees)
		public float fps; // the host's frames over the last second
		public float worstFrameMs; // the longest of them
		public float overlayMs; // what drawing Minecraft's overlay cost a frame, on average over them
		public int slot; // the map's slot in Minecraft's world (1024 blocks along x each)
		public int collisionEpoch; // as in HostState
		public int inputPending; // input ring entries Minecraft hasn't read yet
		public int eventPending; // event ring entries the host hasn't read yet
		public int lightEmitters; // Minecraft's light-emitting blocks the host knows of
		public long collisionPending; // collision ring bytes Minecraft hasn't read yet
		public long renderPending; // render ring bytes the host hasn't read yet
		public int lights; // lights made of those emitters around the player
		public int shadowedLights; // of those, the shadowed point lights (the rest light only characters)
		public float gridZ; // the map's block grid: the source z of minecraft's y = 0 (whole units)

		public void read(MemorySegment s, long at) {
			this.flags = s.get(JAVA_INT, at + HD_FLAGS);
			this.map = text(s, at + HD_MAP, 64);
			this.chapter = text(s, at + HD_CHAPTER, 8);
			this.chapterTitle = text(s, at + HD_CHAPTER_TITLE, 64);
			MemorySegment.copy(s, JAVA_FLOAT, at + HD_ORIGIN, this.origin, 0, 3);
			MemorySegment.copy(s, JAVA_FLOAT, at + HD_ANGLES, this.angles, 0, 3);
			this.fps = s.get(JAVA_FLOAT, at + HD_FPS);
			this.worstFrameMs = s.get(JAVA_FLOAT, at + HD_WORST_FRAME_MS);
			this.overlayMs = s.get(JAVA_FLOAT, at + HD_OVERLAY_MS);
			this.slot = s.get(JAVA_INT, at + HD_SLOT);
			this.collisionEpoch = s.get(JAVA_INT, at + HD_COLLISION_EPOCH);
			this.inputPending = s.get(JAVA_INT, at + HD_INPUT_PENDING);
			this.eventPending = s.get(JAVA_INT, at + HD_EVENT_PENDING);
			this.lightEmitters = s.get(JAVA_INT, at + HD_LIGHT_EMITTERS);
			this.collisionPending = s.get(JAVA_LONG, at + HD_COLLISION_PENDING);
			this.renderPending = s.get(JAVA_LONG, at + HD_RENDER_PENDING);
			this.lights = s.get(JAVA_INT, at + HD_LIGHTS);
			this.shadowedLights = s.get(JAVA_INT, at + HD_SHADOWED_LIGHTS);
			this.gridZ = s.get(JAVA_FLOAT, at + HD_GRID_Z);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + HD_FLAGS, this.flags);
			putText(s, at + HD_MAP, 64, this.map);
			putText(s, at + HD_CHAPTER, 8, this.chapter);
			putText(s, at + HD_CHAPTER_TITLE, 64, this.chapterTitle);
			putFloats(s, at + HD_ORIGIN, this.origin, 3);
			putFloats(s, at + HD_ANGLES, this.angles, 3);
			s.set(JAVA_FLOAT, at + HD_FPS, this.fps);
			s.set(JAVA_FLOAT, at + HD_WORST_FRAME_MS, this.worstFrameMs);
			s.set(JAVA_FLOAT, at + HD_OVERLAY_MS, this.overlayMs);
			s.set(JAVA_INT, at + HD_SLOT, this.slot);
			s.set(JAVA_INT, at + HD_COLLISION_EPOCH, this.collisionEpoch);
			s.set(JAVA_INT, at + HD_INPUT_PENDING, this.inputPending);
			s.set(JAVA_INT, at + HD_EVENT_PENDING, this.eventPending);
			s.set(JAVA_INT, at + HD_LIGHT_EMITTERS, this.lightEmitters);
			s.set(JAVA_LONG, at + HD_COLLISION_PENDING, this.collisionPending);
			s.set(JAVA_LONG, at + HD_RENDER_PENDING, this.renderPending);
			s.set(JAVA_INT, at + HD_LIGHTS, this.lights);
			s.set(JAVA_INT, at + HD_SHADOWED_LIGHTS, this.shadowedLights);
			s.set(JAVA_FLOAT, at + HD_GRID_Z, this.gridZ);
			s.asSlice(at + 0xE4, 4).fill((byte) 0); // pad
		}

		public void copyFrom(HostDebug other) {
			this.flags = other.flags;
			this.map = other.map;
			this.chapter = other.chapter;
			this.chapterTitle = other.chapterTitle;
			System.arraycopy(other.origin, 0, this.origin, 0, 3);
			System.arraycopy(other.angles, 0, this.angles, 0, 3);
			this.fps = other.fps;
			this.worstFrameMs = other.worstFrameMs;
			this.overlayMs = other.overlayMs;
			this.slot = other.slot;
			this.collisionEpoch = other.collisionEpoch;
			this.inputPending = other.inputPending;
			this.eventPending = other.eventPending;
			this.lightEmitters = other.lightEmitters;
			this.collisionPending = other.collisionPending;
			this.renderPending = other.renderPending;
			this.lights = other.lights;
			this.shadowedLights = other.shadowedLights;
			this.gridZ = other.gridZ;
		}
	}

	// HostDebugServer: read, written and copied whole (in OFF_HOST_DEBUG)
	public static class HostDebugServer {
		public int entityCount; // the host's edicts in use
		public int targetIndex; // the entity under the crosshair: its entity index (0: it has none)
		public int health; // its health and maximum health
		public int maxHealth;
		public float distance; // from the player's eye, host units
		// how a character feels about the player: Source's Disposition_t (1 hate, 2 fear, 3 like,
		// 4 neutral); 0: not a character
		public int relation;
		// Source's NPC_STATE (1 idle, 2 alert, 3 combat, 4 script, 5 play dead, 6 held by a barnacle,
		// 7 dead); 0: not an npc
		public int npcState;
		public String targetClass = ""; // empty: nothing under the crosshair (the world doesn't count)
		public String targetName = ""; // its map name; empty: none
		public String schedule = ""; // what an npc is doing (its AI schedule)

		public void read(MemorySegment s, long at) {
			this.entityCount = s.get(JAVA_INT, at + HDS_ENTITY_COUNT);
			this.targetIndex = s.get(JAVA_INT, at + HDS_TARGET_INDEX);
			this.health = s.get(JAVA_INT, at + HDS_HEALTH);
			this.maxHealth = s.get(JAVA_INT, at + HDS_MAX_HEALTH);
			this.distance = s.get(JAVA_FLOAT, at + HDS_DISTANCE);
			this.relation = s.get(JAVA_INT, at + HDS_RELATION);
			this.npcState = s.get(JAVA_INT, at + HDS_NPC_STATE);
			this.targetClass = text(s, at + HDS_TARGET_CLASS, 48);
			this.targetName = text(s, at + HDS_TARGET_NAME, 48);
			this.schedule = text(s, at + HDS_SCHEDULE, 48);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + HDS_ENTITY_COUNT, this.entityCount);
			s.set(JAVA_INT, at + HDS_TARGET_INDEX, this.targetIndex);
			s.set(JAVA_INT, at + HDS_HEALTH, this.health);
			s.set(JAVA_INT, at + HDS_MAX_HEALTH, this.maxHealth);
			s.set(JAVA_FLOAT, at + HDS_DISTANCE, this.distance);
			s.set(JAVA_INT, at + HDS_RELATION, this.relation);
			s.set(JAVA_INT, at + HDS_NPC_STATE, this.npcState);
			putText(s, at + HDS_TARGET_CLASS, 48, this.targetClass);
			putText(s, at + HDS_TARGET_NAME, 48, this.targetName);
			putText(s, at + HDS_SCHEDULE, 48, this.schedule);
		}

		public void copyFrom(HostDebugServer other) {
			this.entityCount = other.entityCount;
			this.targetIndex = other.targetIndex;
			this.health = other.health;
			this.maxHealth = other.maxHealth;
			this.distance = other.distance;
			this.relation = other.relation;
			this.npcState = other.npcState;
			this.targetClass = other.targetClass;
			this.targetName = other.targetName;
			this.schedule = other.schedule;
		}
	}

	// WeaponRecord: read and written whole
	//   id: WeaponId
	//   clip: rounds in the clip; -1: no clip (it fires from the reserve, or uses no ammo)
	//   maxClip: the clip's size; -1: no clip
	//   ammo: primary rounds in reserve; -1: it uses no ammo (crowbar, gravity gun)
	//   maxAmmo: the most primary rounds the player can carry
	//   ammo2: secondary rounds (SMG grenades, AR2 balls); -1: none
	//   flags: WeaponRecordFlags
	public record WeaponRecord(int id, int clip, int maxClip, int ammo, int maxAmmo, int ammo2, int maxAmmo2, int flags) implements WeaponTable.Weapon {
		public static WeaponRecord read(MemorySegment s, long at) {
			int id = s.get(JAVA_INT, at + WT_R_ID);
			int clip = s.get(JAVA_INT, at + WT_R_CLIP);
			int maxClip = s.get(JAVA_INT, at + WT_R_MAX_CLIP);
			int ammo = s.get(JAVA_INT, at + WT_R_AMMO);
			int maxAmmo = s.get(JAVA_INT, at + WT_R_MAX_AMMO);
			int ammo2 = s.get(JAVA_INT, at + WT_R_AMMO2);
			int maxAmmo2 = s.get(JAVA_INT, at + WT_R_MAX_AMMO2);
			int flags = s.get(JAVA_INT, at + WT_R_FLAGS);
			return new WeaponRecord(id, clip, maxClip, ammo, maxAmmo, ammo2, maxAmmo2, flags);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + WT_R_ID, this.id);
			s.set(JAVA_INT, at + WT_R_CLIP, this.clip);
			s.set(JAVA_INT, at + WT_R_MAX_CLIP, this.maxClip);
			s.set(JAVA_INT, at + WT_R_AMMO, this.ammo);
			s.set(JAVA_INT, at + WT_R_MAX_AMMO, this.maxAmmo);
			s.set(JAVA_INT, at + WT_R_AMMO2, this.ammo2);
			s.set(JAVA_INT, at + WT_R_MAX_AMMO2, this.maxAmmo2);
			s.set(JAVA_INT, at + WT_R_FLAGS, this.flags);
		}
	}

	// MobRecord: read and written whole
	//   id: the Minecraft entity id, stable while the mob exists
	//   flags: MobFlags
	//   x: feet, MC coords
	//   yaw: MC degrees
	//   width: blocks
	//   height: blocks
	//   health: Minecraft points
	public record MobRecord(int id, int flags, float x, float y, float z, float yaw, float width, float height, float health, float maxHealth) {
		public static MobRecord read(MemorySegment s, long at) {
			int id = s.get(JAVA_INT, at + MR_ID);
			int flags = s.get(JAVA_INT, at + MR_FLAGS);
			float x = s.get(JAVA_FLOAT, at + MR_X);
			float y = s.get(JAVA_FLOAT, at + MR_Y);
			float z = s.get(JAVA_FLOAT, at + MR_Z);
			float yaw = s.get(JAVA_FLOAT, at + MR_YAW);
			float width = s.get(JAVA_FLOAT, at + MR_WIDTH);
			float height = s.get(JAVA_FLOAT, at + MR_HEIGHT);
			float health = s.get(JAVA_FLOAT, at + MR_HEALTH);
			float maxHealth = s.get(JAVA_FLOAT, at + MR_MAX_HEALTH);
			return new MobRecord(id, flags, x, y, z, yaw, width, height, health, maxHealth);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + MR_ID, this.id);
			s.set(JAVA_INT, at + MR_FLAGS, this.flags);
			s.set(JAVA_FLOAT, at + MR_X, this.x);
			s.set(JAVA_FLOAT, at + MR_Y, this.y);
			s.set(JAVA_FLOAT, at + MR_Z, this.z);
			s.set(JAVA_FLOAT, at + MR_YAW, this.yaw);
			s.set(JAVA_FLOAT, at + MR_WIDTH, this.width);
			s.set(JAVA_FLOAT, at + MR_HEIGHT, this.height);
			s.set(JAVA_FLOAT, at + MR_HEALTH, this.health);
			s.set(JAVA_FLOAT, at + MR_MAX_HEALTH, this.maxHealth);
			s.asSlice(at + 0x28, 8).fill((byte) 0); // pad
		}
	}

	// WaterProbe: read and written whole
	//   originX: Minecraft block column of surface[0]
	//   y: the height it was probed around
	//   surface: [z * size + x]: MC y of the water surface; NO_WATER: none
	public record WaterProbe(int originX, int originZ, float y, float[] surface) {
		public static WaterProbe read(MemorySegment s, long at) {
			int originX = s.get(JAVA_INT, at + WP_ORIGIN_X);
			int originZ = s.get(JAVA_INT, at + WP_ORIGIN_Z);
			float y = s.get(JAVA_FLOAT, at + WP_Y);
			float[] surface = floats(s, at + WP_SURFACE, 64);
			return new WaterProbe(originX, originZ, y, surface);
		}

		public void write(MemorySegment s, long at) {
			s.set(JAVA_INT, at + WP_ORIGIN_X, this.originX);
			s.set(JAVA_INT, at + WP_ORIGIN_Z, this.originZ);
			s.set(JAVA_FLOAT, at + WP_Y, this.y);
			s.asSlice(at + 0x0C, 4).fill((byte) 0); // pad
			putFloats(s, at + WP_SURFACE, this.surface, 64);
		}
	}

	// a NUL-terminated UTF-8 string of at most bytes
	private static String text(MemorySegment s, long at, int bytes) {
		byte[] raw = new byte[bytes];
		MemorySegment.copy(s, JAVA_BYTE, at, raw, 0, bytes);
		int length = 0;
		while (length < bytes && raw[length] != 0) {
			length++;
		}
		return new String(raw, 0, length, StandardCharsets.UTF_8);
	}

	// the string's UTF-8, cut to bytes - 1, then NULs
	private static void putText(MemorySegment s, long at, int bytes, String text) {
		byte[] raw = text.getBytes(StandardCharsets.UTF_8);
		int length = Math.min(raw.length, bytes - 1);
		MemorySegment.copy(raw, 0, s, JAVA_BYTE, at, length);
		s.asSlice(at + length, bytes - length).fill((byte) 0);
	}

	private static float[] floats(MemorySegment s, long at, int count) {
		float[] values = new float[count];
		MemorySegment.copy(s, JAVA_FLOAT, at, values, 0, count);
		return values;
	}

	// values, then zeros up to count (none given: all zeros)
	private static void putFloats(MemorySegment s, long at, float @Nullable [] values, int count) {
		int given = values == null ? 0 : Math.min(values.length, count);
		if (given > 0) {
			MemorySegment.copy(values, 0, s, JAVA_FLOAT, at, given);
		}
		s.asSlice(at + given * JAVA_FLOAT.byteSize(), (count - given) * JAVA_FLOAT.byteSize()).fill((byte) 0);
	}
}
