name: Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  clang-format:
    name: clang-format
    runs-on: windows-2025
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: clang-format 22.1.3
        shell: powershell
        run: ./.github/scripts/pinned.ps1 clang-format
      - name: make lint
        shell: powershell
        run: ./tools/format.ps1 -Check
